@startuml
title Integratie op bronnen
footer: OpenWoo.app
header: OpenWoo.app



' Services (Laag 4)
frame "Services (Laag 4)" {
    process "OpenWoo Service"  as OWS #1abc9c
}

' Integratie (Laag 3)
frame "API (Laag 3)" {
    database "Open Index" as OI #1abc9c
}

' Bronnen (Laag 2)
frame "Bronnen" {
    component "Zaaksysteem" as Zaaksysteem  #cce5ff
    component "CMS" as CMS  #cce5ff
    component "Raads informatie systeem" as Raadsinfo  #cce5ff
    component "eDepot" as eDepot  #cce5ff
    component "DMS" as DMS  #cce5ff
    component "VTH" as VTH  #cce5ff
}

' Relationships
OWS ..> OI: Slaat op in

OWS -down-> CMS : Scrapes periodically\nUses as source
OWS -down-> Zaaksysteem : Scrapes periodically\nUses as source
OWS -down-> Raadsinfo : Scrapes periodically\nUses as source
OWS -down-> eDepot : Scrapes periodically\nUses as source
OWS -down-> DMS : Scrapes periodically\nUses as source
OWS -down-> VTH : Scrapes periodically\nUses as source

' Notifications
CMS -up-> OWS : Notifies of changes or deletes
Zaaksysteem -up-> OWS : Notifies of changes or deletes

@enduml