@startuml
title Publiceren vanuit Zaaksysteem
footer: OpenWoo.app
header: OpenWoo.app

' Publicatie platformen (Laag 5 UI)
frame "Publicatie platformen " {
    interface "Zoek pagina" as Searchsite #1abc9c
}

' Services(Laag 4)
frame "Services" {
    process "OpenWoo Service"  as OWS #1abc9c
}

' Integratie (Laag 3)
frame "Integratie" {
    database "Open Index"  as OI #1abc9c
}

' Bronnen (Laag 2)
frame "API" {
    database "Zaaksysteem (ZGW)" as ZRC #cce5ff
}


Searchsite -down-> OI : Bevraagd (API)
OWS -down-> ZRC: Indexeerd
OWS ..> OI: Slaat op in
ZRC ..-> OWS : Notifies of changes or deletes

@enduml
