name: Branch Protection

on:
  pull_request:
    branches: [main, beta]

jobs:
  branch-protection:
    uses: ConductionNL/woo-website-template/.github/workflows/branch-protection-check.yml@update-workflow
    secrets: inherit
